# Generated by Django 2.0.2 on 2018-02-14 16:52

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsite',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.LearningSiteCategory'),
        ),
        migrations.AlterField(
            model_name='learningsite',
            name='defunct',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningsite',
            name='established',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningsite',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='learningsite',
            name='verified_modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
