# Generated by Django 2.0.2 on 2018-02-20 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_learning_site_required_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('latlng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('digital_object', models.ManyToManyField(blank=True, to='main.DigitalObject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
