# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180205_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivalRespository',
            new_name='ArchivalRepository',
        ),
    ]
