# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180205_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalcollection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='archivalcollection',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='archivalrepository',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='archivalrepository',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='digitalobject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='digitalobject',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='learningsite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='learningsite',
            name='last_modified_by',
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/'),
        ),
    ]
