# Generated by Django 2.0.2 on 2018-02-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsite',
            name='founder',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningsite',
            name='instructional_level',
            field=models.TextField(blank=True, null=True),
        ),
    ]
