# Generated by Django 2.0.2 on 2018-02-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180220_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
