# Generated by Django 2.0.2 on 2018-02-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180221_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalobject',
            name='datestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
