# Generated by Django 2.0.2 on 2018-02-25 00:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point

POINT = Point(-104.9903, 39.7392, srid=4326)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180221_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalrepository',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='archivalrepository',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='archivalrepository',
            name='verified_modified_at',
        ),
        migrations.AddField(
            model_name='archivalcollection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivalrepository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='finding_aid_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='learning_sites',
            field=models.ManyToManyField(blank=True, to='main.LearningSite'),
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='linear_feet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='record_format',
            field=models.ManyToManyField(blank=True, to='main.ArchivalRecordFormat'),
        ),
        migrations.AlterField(
            model_name='archivalrepository',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(default=POINT, srid=4326),
            preserve_default=False,
        ),
    ]
