# Generated by Django 2.0.2 on 2018-02-28 15:42

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180224_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='archivalcollection',
            name='title',
            field=models.TextField(verbose_name='Collection Title'),
        ),
        migrations.AlterField(
            model_name='archivalrepository',
            name='latlng',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(1, 1), srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivalrepository',
            name='title',
            field=models.TextField(unique=True, verbose_name='Repository Title'),
        ),
        migrations.AddField(
            model_name='learningsite',
            name='footnotes',
            field=models.ManyToManyField(blank=True, to='main.Footnote'),
        ),
    ]
