# Generated by Django 2.0.2 on 2018-03-01 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20180228_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalcollection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivalcollection',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivalrepository',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivalrepository',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repository_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningsite',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_modified_by', to=settings.AUTH_USER_MODEL),
        )
    ]
