# Generated by Django 2.0.2 on 2018-03-01 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180301_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edtf_format', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Extended Date Format',
            },
        )
    ]
