# Generated by Django 2.0.2 on 2018-03-02 14:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180301_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsite',
            name='defunct',
        ),
        migrations.RemoveField(
            model_name='learningsite',
            name='established',
        ),
    ]
