# Generated by Django 2.0.2 on 2018-03-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180302_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsite',
            name='defunct',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_defunct', to='main.ExtendedDate'),
        ),
        migrations.AddField(
            model_name='learningsite',
            name='established',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_established', to='main.ExtendedDate'),
        ),
    ]
