# Generated by Django 2.0.2 on 2018-03-02 19:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180302_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='ordinal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name='footnote',
            options={'ordering': ['ordinal']},
        ),
    ]
