# Generated by Django 2.0.2 on 2018-03-06 01:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180305_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='source',
            field=models.TextField(blank=True, help_text='Where did you find this photo?', null=True),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='datestamp',
            field=models.DateField(blank=True, null=True, verbose_name='Date Taken'),
        ),
        migrations.AlterField(
            model_name='digitalobject',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
