# Generated by Django 2.0.3 on 2018-03-08 21:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180305_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalcollection',
            name='inclusive_end',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_end', to='main.ExtendedDate'),
        ),
        migrations.AddField(
            model_name='archivalcollection',
            name='inclusive_start',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_start', to='main.ExtendedDate'),
        )
    ]
