# Generated by Django 2.0.3 on 2018-03-10 16:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180308_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalobject',
            name='date_taken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ExtendedDate', verbose_name='Date Taken'),
        )
    ]
