# Generated by Django 2.0.3 on 2018-03-10 17:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def migrate_lat_lng(apps, schema_editor):
        Place = apps.get_model('main', 'Place')
        ArchivalRepository = apps.get_model('main', 'ArchivalRepository')
        for repo in ArchivalRepository.objects.all():
            p = Place.objects.create(title='Temporary', latlng=repo.latlng)
            repo.place = p
            repo.save()

    dependencies = [
        ('main', '0018_auto_20180310_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalrepository',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Place'),
        ),
        migrations.RunPython(migrate_lat_lng),
        migrations.RemoveField(
            model_name='archivalrepository',
            name='latlng',
        )
    ]
