# Generated by Django 2.0.3 on 2018-03-10 18:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_lat_lng(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Place = apps.get_model('main', 'Place')
        LearningSite = apps.get_model('main', 'LearningSite')
        for site in LearningSite.objects.all():
            p = Place.objects.create(title='Temporary', latlng=site.latlng)
            site.place.add(p)

    dependencies = [
        ('main', '0019_auto_20180310_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsite',
            name='place',
            field=models.ManyToManyField(blank=True, to='main.Place'),
        ),
        migrations.RunPython(migrate_lat_lng),
        migrations.RemoveField(
            model_name='learningsite',
            name='latlng',
        )
    ]
