# Generated by Django 2.0.3 on 2018-03-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20180310_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
