# Generated by Django 2.0.3 on 2018-03-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180316_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='digital_object',
        ),
        migrations.RemoveField(
            model_name='place',
            name='notes',
        ),
        migrations.AddField(
            model_name='place',
            name='end_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_end_date', to='main.ExtendedDate'),
        ),
        migrations.AddField(
            model_name='place',
            name='start_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_start_date', to='main.ExtendedDate'),
        ),
    ]
