# Generated by Django 2.0.4 on 2018-04-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180317_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSiteRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='learningsite',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_learningsite_children_+', to='main.LearningSite'),
        ),
        migrations.AddField(
            model_name='learningsiterelationship',
            name='site_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_one', to='main.LearningSite'),
        ),
        migrations.AddField(
            model_name='learningsiterelationship',
            name='site_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_two', to='main.LearningSite'),
        ),
    ]
