# Generated by Django 2.0.5 on 2018-05-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_learningsitecategory_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivalcollection',
            options={'ordering': ['collection_title'], 'verbose_name': 'Archival Collection'},
        ),
        migrations.RenameField(
            model_name='archivalcollection',
            old_name='title',
            new_name='collection_title',
        ),
    ]
