# Generated by Django 2.0.6 on 2018-06-14 15:25

from django.db import migrations


def make_children_associates(apps, schema_editor):
    LearningSite = apps.get_model('main', 'LearningSite')
    LearningSiteRelationship = apps.get_model(
        'main', 'LearningSiteRelationship')
    for site in LearningSite.objects.all():
        for child in site.children.all():
            LearningSiteRelationship.objects.create(
                site_one=site, site_two=child)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20180502_2025'),
    ]

    operations = [
        migrations.RunPython(make_children_associates),
    ]
