# Generated by Django 2.0.6 on 2018-06-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_associates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningsite',
            name='children',
        ),
    ]
