# Generated by Django 2.0.7 on 2018-07-06 14:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_learningsite_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalCollectionSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.TextField(verbose_name='Your Name')),
                ('person_title', models.TextField(verbose_name='Your Title')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
                ('repository_title', models.TextField()),
                ('collection_title', models.TextField()),
                ('latlng', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('finding_aid_url', models.URLField(blank=True, null=True)),
                ('linear_feet', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('archival_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ArchivalCollection')),
                ('inclusive_end', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_end', to='main.ExtendedDate')),
                ('inclusive_start', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_start', to='main.ExtendedDate')),
                ('record_format', models.ManyToManyField(blank=True, to='main.ArchivalRecordFormat')),
            ],
            options={
                'ordering': ['repository_title', 'collection_title'],
            },
        ),
    ]
