# Generated by Django 2.0.7 on 2018-07-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_learningsite_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivalcollection',
            name='inclusive_end_date',
        ),
        migrations.RemoveField(
            model_name='archivalcollection',
            name='inclusive_start_date',
        ),
    ]
