# Generated by Django 2.0.7 on 2018-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_archivalcollectionsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeddate',
            name='lower',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='extendeddate',
            name='upper',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='archivalcollectionsuggestion',
            name='title',
            field=models.TextField(verbose_name='Address'),
        ),
    ]
