# Generated by Django 2.1 on 2018-08-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180725_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsite',
            name='is_defunct',
            field=models.BooleanField(default=True, help_text='Does this learning site still exist?'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_ended',
            field=models.BooleanField(default=True, help_text='Is the site or archive still at this location?'),
        ),
    ]
