name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
          python-version: [3.6]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Update environment
        run: sudo apt update
      - name: Install Spatialite and libgdal
        run: sudo apt-get install libgdal-dev libsqlite3-mod-spatialite
      - name: Build with Makefile
        run: make
